// Code generated by mockery v2.30.16. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/AntonioKichaev/internal/entity"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/AntonioKichaev/internal/repository"
)

// AccountRepository is an autogenerated mock type for the AccountRepository type
type AccountRepository struct {
	mock.Mock
}

// AddPoint provides a mock function with given fields: ctx, dto
func (_m *AccountRepository) AddPoint(ctx context.Context, dto repository.AddPointDTO) error {
	ret := _m.Called(ctx, dto)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.AddPointDTO) error); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateBalance provides a mock function with given fields: ctx, dto
func (_m *AccountRepository) CreateBalance(ctx context.Context, dto repository.CreateBalanceDTO) error {
	ret := _m.Called(ctx, dto)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateBalanceDTO) error); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBalanceByID provides a mock function with given fields: ctx, dto
func (_m *AccountRepository) GetBalanceByID(ctx context.Context, dto repository.GetBalanceByIDDTO) (*entity.SaveBalance, error) {
	ret := _m.Called(ctx, dto)

	var r0 *entity.SaveBalance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetBalanceByIDDTO) (*entity.SaveBalance, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetBalanceByIDDTO) *entity.SaveBalance); ok {
		r0 = rf(ctx, dto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.SaveBalance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.GetBalanceByIDDTO) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWithdrawsByUserID provides a mock function with given fields: ctx, dto
func (_m *AccountRepository) GetWithdrawsByUserID(ctx context.Context, dto repository.GetWithdrawsByUserIDDTO) ([]entity.Withdrawn, error) {
	ret := _m.Called(ctx, dto)

	var r0 []entity.Withdrawn
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetWithdrawsByUserIDDTO) ([]entity.Withdrawn, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetWithdrawsByUserIDDTO) []entity.Withdrawn); ok {
		r0 = rf(ctx, dto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Withdrawn)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.GetWithdrawsByUserIDDTO) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAccount provides a mock function with given fields: ctx, balance
func (_m *AccountRepository) UpdateAccount(ctx context.Context, balance entity.SaveBalance) error {
	ret := _m.Called(ctx, balance)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.SaveBalance) error); ok {
		r0 = rf(ctx, balance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAccountRepository creates a new instance of AccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountRepository {
	mock := &AccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
